version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db_example
    networks:
      - mongo-network
    command: >
      bash -c "
      mongod --fork --logpath /var/log/mongodb.log;
      mongo db_example --eval 'db.createUser({user: \"admin\", pwd: \"admin\", roles: [{role: \"readWrite\", db: \"db_example\"}]})';
      mongod --shutdown;
      mongod --bind_ip_all
      "

networks:
  mongo-network: